stages:
  - deploy

deploy_to_server:
  stage: deploy
  script:
    - sshpass -p $DEPLOY_PASS ssh -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git pull origin main"
  only:
    - main